spring:
  profiles:
    active: pro


mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.kendall.dota2dataservice.pojo.model
  # mapper xml实现扫描路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  config-location: classpath:mybatis/mybatis-config.xml

# DDService 配置
dota2:
  #fundatasdk api key and secret
  key: e45a0b71353b4bf
  secret: bdae48267b6f4e4bbbae324afff4a88

# httpclient 连接池配置
http:
  maxTotal: 200
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
