package com.kendall.dota2dataservice.dao;

import com.kendall.dota2dataservice.pojo.model.Hero;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HeroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbg.generated
     */
    int insert(Hero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbg.generated
     */
    Hero selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbg.generated
     */
    List<Hero> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hero record);

    void batchInsert(@Param("heroes") List<Hero> heroes);
}