package com.kendall.dota2dataservice.pojo.model;

import java.io.Serializable;
import java.util.Date;

public class Item implements Serializable {
    /**
     * This field corresponds to the database column item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field corresponds to the database column item.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This field corresponds to the database column item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field corresponds to the database column item.local_name
     *
     * @mbg.generated
     */
    private String localName;

    /**
     * This field corresponds to the database column item.qual
     *
     * @mbg.generated
     */
    private String qual;

    /**
     * This field corresponds to the database column item.mc
     *
     * @mbg.generated
     */
    private String mc;

    /**
     * This field corresponds to the database column item.cd
     *
     * @mbg.generated
     */
    private String cd;

    /**
     * This field corresponds to the database column item.attrib
     *
     * @mbg.generated
     */
    private String attrib;

    /**
     * This field corresponds to the database column item.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * This field corresponds to the database column item.lore
     *
     * @mbg.generated
     */
    private String lore;

    /**
     * This field corresponds to the database column item.components
     *
     * @mbg.generated
     */
    private String components;

    /**
     * This field corresponds to the database column item.created
     *
     * @mbg.generated
     */
    private Byte created;

    /**
     * This field corresponds to the database column item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field corresponds to the database column item.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field corresponds to the database table item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img
     *
     * @return the value of item.img
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img
     *
     * @param img the value for item.img
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.local_name
     *
     * @return the value of item.local_name
     * @mbg.generated
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.local_name
     *
     * @param localName the value for item.local_name
     * @mbg.generated
     */
    public void setLocalName(String localName) {
        this.localName = localName == null ? null : localName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.qual
     *
     * @return the value of item.qual
     * @mbg.generated
     */
    public String getQual() {
        return qual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.qual
     *
     * @param qual the value for item.qual
     * @mbg.generated
     */
    public void setQual(String qual) {
        this.qual = qual == null ? null : qual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.mc
     *
     * @return the value of item.mc
     * @mbg.generated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.mc
     *
     * @param mc the value for item.mc
     * @mbg.generated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.cd
     *
     * @return the value of item.cd
     * @mbg.generated
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.cd
     *
     * @param cd the value for item.cd
     * @mbg.generated
     */
    public void setCd(String cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attrib
     *
     * @return the value of item.attrib
     * @mbg.generated
     */
    public String getAttrib() {
        return attrib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attrib
     *
     * @param attrib the value for item.attrib
     * @mbg.generated
     */
    public void setAttrib(String attrib) {
        this.attrib = attrib == null ? null : attrib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.desc
     *
     * @return the value of item.desc
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.desc
     *
     * @param desc the value for item.desc
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.lore
     *
     * @return the value of item.lore
     * @mbg.generated
     */
    public String getLore() {
        return lore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.lore
     *
     * @param lore the value for item.lore
     * @mbg.generated
     */
    public void setLore(String lore) {
        this.lore = lore == null ? null : lore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.components
     *
     * @return the value of item.components
     * @mbg.generated
     */
    public String getComponents() {
        return components;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.components
     *
     * @param components the value for item.components
     * @mbg.generated
     */
    public void setComponents(String components) {
        this.components = components == null ? null : components.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created
     *
     * @return the value of item.created
     * @mbg.generated
     */
    public Byte getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created
     *
     * @param created the value for item.created
     * @mbg.generated
     */
    public void setCreated(Byte created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", img=").append(img);
        sb.append(", name=").append(name);
        sb.append(", localName=").append(localName);
        sb.append(", qual=").append(qual);
        sb.append(", mc=").append(mc);
        sb.append(", cd=").append(cd);
        sb.append(", attrib=").append(attrib);
        sb.append(", desc=").append(desc);
        sb.append(", lore=").append(lore);
        sb.append(", components=").append(components);
        sb.append(", created=").append(created);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}